apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migrate
  namespace: dev
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: alembic
          image: sarialbebeto/alembic-migrate:latest
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - |
              until pg_isready -h fastapi-dev-db -p 5432 -U fastapi_traefik; do
                echo 'Waiting for Postgres...'
                sleep 10
              done
              export DATABASE_URL="postgresql://fastapi_traefik:${DB_PASSWORD}@fastapi-dev-db:5432/fastapi_traefik"
              echo "DATABASE_URL=$DATABASE_URL"
              cd /workspace
              echo "Alembic versions:"
              ls -l alembic/versions/
              echo 'Alembic current BEFORE:'
              alembic current
              echo 'Alembic history BEFORE:'
              alembic history
              echo 'Running alembic upgrade head:'
              alembic upgrade head
              echo 'Alembic current AFTER:'
              alembic current
              echo 'Alembic history AFTER:'
              alembic history
              echo 'DB tables after migration:'
              apt-get update && apt-get install -y postgresql-client
              PGPASSWORD=${DB_PASSWORD} psql -h fastapi-dev-db -U fastapi_traefik -d fastapi_traefik -c '\dt'
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastapi-dev-db
                  key: POSTGRES_PASSWORD
