[entryPoints]
  [entryPoints.web]
    address = ":80"
  #[entryPoints.web.http]
  #  [entryPoints.web.http.redirections]
  #    [entryPoints.web.http.redirections.entryPoint]
  #      to = "websecure"
  #      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.tls]
       certFile = "/letsencrypt/fullchain.pem"
       keyFile = "/letsencrypt/privkey.pem"

[accessLog]

[api]
dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "tsamosarial@yahoo.fr"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"

