apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "fastapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: web
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
